import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hero Journey',
  description: 'Generated by Next 14'
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <Head>
        <meta name="color-scheme" content="dark" />
        <meta name="theme-color" content="#000000" />
      </Head>

      <body className={inter.className} style={{ margin: '0px' }}>
        {children}
      </body>
    </html>
  )
}
